import type { TrackerData } from "@/lib/types";

/**
 * Bumped whenever the seed below changes. A browser reconciles itself against
 * the seed once per revision — deliberately *not* keyed to the persist store's
 * `version`, which tracks the shape of the data rather than its content and can
 * be stamped forward by an ordinary write while the content is still stale.
 */
export const SEED_REVISION = 10;

/** Day 1 of the programme, as logged in the original workbook. */
export const DAY_ONE = "2026-08-11";
export const DAY_TWO = "2026-08-12";
export const DAY_THREE = "2026-08-13";
export const DAY_FOUR = "2026-08-14";
export const DAY_FIVE = "2026-08-15";
/** Sunday the 16th was a rest day — Day 6 is the Monday. */
export const DAY_SIX = "2026-08-17";
export const DAY_SEVEN = "2026-08-18";
export const DAY_EIGHT = "2026-08-19";

/**
 * The programme so far, carried over from the source workbooks.
 *
 * Day 1 — `…_Day1_Completed.xlsx`: eleven blocks, 40 questions, 39 correct.
 * Day 2 — `…_Day2_Completed.xlsx`: seventeen blocks over four sessions, 42
 *   questions, all correct.
 * Day 3 — `…_Day3_Enhanced.xlsx`: eleven blocks over five sessions, 40
 *   questions, 34 correct. That workbook also revised the Topic Master
 *   wholesale — new targets, priorities and statuses — and added the Formula &
 *   Shortcuts sheet now served at `/formulas` (see `lib/formulas.ts`).
 * Day 4 — `…_Day4_Enhanced.xlsx`: eight blocks over four sessions, 40
 *   questions, 39 correct, plus nine formulas for time & work,
 *   time-speed-distance and simple interest.
 * Day 5 — `…_Day5_Enhanced.xlsx`: nine blocks, 46 questions, 44 correct — the
 *   first day run entirely at Moderate — plus ten formulas for compound
 *   interest, averages, successive percentages and partnership.
 * Day 6 — `…_Day6_Enhanced_17-08-2026.xlsx`: six blocks, 40 questions, all
 *   correct, including the first ever above Moderate — plus ten formulas for
 *   relative speed, trains and boats & streams.
 * Day 7 — `…_Day7_Enhanced_18-08-2026.xlsx`: eight blocks over four rounds, 40
 *   questions, 37 correct, including the first Hard round — plus eight exam-trap
 *   notes covering collective nouns, uncountable nouns and answer format.
 * Day 8 — `…_Day8_Enhanced_19-08-2026.xlsx`: five blocks over four rounds, 40
 *   questions, 39 correct — the day Profit & Loss and Time & Work were finally
 *   revisited, both perfect — plus twelve formulas restating profit/loss and
 *   adding data interpretation and uncountable nouns.
 *
 * `Day_2_Elite_Report.xlsx` was an interim snapshot of the same day (25
 * questions, coarser topics, one ~20-minute total). The completed workbook
 * supersedes it entirely, so those rows are gone rather than double-counted —
 * and with them the invented per-block times, since the completed workbook
 * records no times at all.
 *
 * Seven things were reconciled on the way in:
 *
 * 1. Day 1's Topic Master named three topics differently from the practice rows
 *    it describes ("Basic Grammar" vs "Grammar Basics", "Odd One Out" vs "Odd
 *    One Out / Number Patterns", "Percentage-Fraction Conversions" vs
 *    "Percentage Shortcuts"), so nothing joined. The names here follow the
 *    practice rows; the descriptive detail moved into the notes.
 * 2. Day 2's Session Log row says 40 questions, but the seventeen Daily
 *    Performance rows it summarises add up to 42. Same class of drift as Day 1's
 *    34-vs-35: the per-block rows are the primary record and win.
 * 3. Four Day 2 topic names are the same topic as an existing one under a
 *    different label — "Simplification (BODMAS)", "Squares & Cubes Revision",
 *    "Percentages Revision" and the Elite Challenge's bare "Grammar". Each is
 *    filed under its parent topic so the results join, with the distinguishing
 *    detail kept in the notes. Day 3 adds two more of the same kind ("Ratio
 *    Revision" and a bare "Grammar").
 * 4. Day 3's Topic Master marks "Complex Number Series" Strong and explains it
 *    with "Advanced series solved correctly" — they are one topic under two
 *    names. Only "Advanced Series" survives, since that is what the practice
 *    rows call it.
 * 5. Day 5's Session Log row says 40 questions with 37 correct, but its nine
 *    Daily Performance rows add up to 46 and 44. The per-block rows win, as
 *    with Day 1 and Day 2 — the day total looks like it was written to the
 *    40-question goal rather than counted from the blocks.
 * 6. Two Day 6 blocks each bundle two topics — "Relative Speed & Boats" and
 *    "Average & Compound Interest" — while that workbook's Topic Master lists
 *    the four separately. Ten questions cannot be split between two topics
 *    without inventing the split, so each block stays whole under its combined
 *    name and gets its own Topic Master row.
 * 7. Day 7's Topic Master adds an "English Grammar" row alongside the existing
 *    "Basic Grammar" — the same topic again under a second name. Its revisions
 *    are applied to the one row the practice actually joins to.
 */
export const seedData: TrackerData = {
  goals: {
    startDate: DAY_ONE,
    dailyQuestionTarget: 40,
    accuracyTarget: 0.85,
  },
  entries: [
    {
      id: "seed-e1",
      date: DAY_ONE,
      session: "Main + Afternoon",
      subject: "Quantitative Aptitude",
      topic: "Percentages",
      attempted: 10,
      correct: 10,
      difficulty: "Foundation",
      score: 5,
      notes: "Strong fundamentals and mental calculation",
    },
    {
      id: "seed-e2",
      date: DAY_ONE,
      session: "Main + Afternoon",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 5,
      correct: 5,
      difficulty: "Foundation",
      score: 5,
      notes: "Strong pattern recognition",
    },
    {
      id: "seed-e3",
      date: DAY_ONE,
      session: "Afternoon",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 5,
      correct: 5,
      difficulty: "Foundation",
      score: 5,
      notes: "Good basic grammar accuracy",
    },
    {
      id: "seed-e4",
      date: DAY_ONE,
      session: "Afternoon",
      subject: "Quantitative Aptitude",
      topic: "Speed Percentage Drill",
      attempted: 3,
      correct: 3,
      difficulty: "Foundation",
      score: 5,
      notes: "Good mental calculation",
    },
    {
      id: "seed-e5",
      date: DAY_ONE,
      session: "Afternoon",
      subject: "Reasoning",
      topic: "Odd One Out / Number Patterns",
      attempted: 3,
      correct: 2,
      difficulty: "Easy-Moderate",
      score: 3.5,
      notes: "One error identifying the common property",
    },
    {
      id: "seed-e6",
      date: DAY_ONE,
      session: "Afternoon",
      subject: "Quantitative Aptitude",
      topic: "Percentage Shortcuts",
      attempted: 5,
      correct: 5,
      difficulty: "Moderate",
      score: 5,
      notes: "Strong fraction-percentage conversions",
    },
    {
      id: "seed-e7",
      date: DAY_ONE,
      session: "Main",
      subject: "Reasoning",
      topic: "Coding-Decoding",
      attempted: 5,
      correct: 5,
      difficulty: "Foundation",
      score: 5,
      notes: "Correct letter shifts and A-Z wraparound",
    },
    // The four "Goal Completion" questions that closed out Day 1 at the
    // 40-question goal. Topic here holds the question itself, as the workbook
    // recorded it — they surface in Topic Master as practised-but-unlisted.
    {
      id: "seed-e8",
      date: DAY_ONE,
      session: "Goal Completion",
      subject: "Quantitative Aptitude",
      topic: "12.5% of 88",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "Goal completion question",
    },
    {
      id: "seed-e9",
      date: DAY_ONE,
      session: "Goal Completion",
      subject: "Quantitative Aptitude",
      topic: "Reverse percentage (20% increase to 360)",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "Goal completion question",
    },
    {
      id: "seed-e10",
      date: DAY_ONE,
      session: "Goal Completion",
      subject: "Reasoning",
      topic: "Geometric series (×3)",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "Goal completion question",
    },
    {
      id: "seed-e11",
      date: DAY_ONE,
      session: "Goal Completion",
      subject: "English",
      topic: "Correct sentence identification",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "Goal completion question",
    },

    // --- Day 2 · 42/42 across four sessions ---------------------------------
    {
      id: "seed-d2b-1",
      date: DAY_TWO,
      session: "Session 1",
      subject: "Quantitative Aptitude",
      topic: "Simplification",
      attempted: 5,
      correct: 5,
      difficulty: "Easy",
      score: 5,
      notes: "BODMAS — perfect accuracy",
    },
    {
      id: "seed-d2b-2",
      date: DAY_TWO,
      session: "Session 1",
      subject: "Quantitative Aptitude",
      topic: "Approximation",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Correct rounding and estimation",
    },
    {
      id: "seed-d2b-3",
      date: DAY_TWO,
      session: "Session 1",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Fast pattern recognition",
    },
    {
      id: "seed-d2b-4",
      date: DAY_TWO,
      session: "Session 1",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Correct verb and time usage",
    },
    {
      id: "seed-d2b-5",
      date: DAY_TWO,
      session: "Session 1",
      subject: "Quantitative Aptitude",
      topic: "Percentage Shortcuts",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "16⅔% = 1/6 applied correctly",
    },
    {
      id: "seed-d2b-6",
      date: DAY_TWO,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Squares Ending in 5",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Used (n)(n+1)+25 trick",
    },
    {
      id: "seed-d2b-7",
      date: DAY_TWO,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Fast Multiplication",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "999 × 9 shortcut",
    },
    {
      id: "seed-d2b-8",
      date: DAY_TWO,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Square Roots & Percentages",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Fast root recognition",
    },
    {
      id: "seed-d2b-9",
      date: DAY_TWO,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Speed Mock",
      attempted: 5,
      correct: 5,
      difficulty: "Easy-Moderate",
      score: 5,
      notes: "Completed within target time",
    },
    {
      id: "seed-d2b-10",
      date: DAY_TWO,
      session: "Elite Challenge",
      subject: "Quantitative Aptitude",
      topic: "Difference of Squares",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Applied a²−b² identity",
    },
    {
      id: "seed-d2b-11",
      date: DAY_TWO,
      session: "Elite Challenge",
      subject: "Quantitative Aptitude",
      topic: "Mixed Quant",
      attempted: 2,
      correct: 2,
      difficulty: "Moderate",
      score: 5,
      notes: "Root + percentage + reverse percentage",
    },
    {
      id: "seed-d2b-12",
      date: DAY_TWO,
      session: "Elite Challenge",
      subject: "Reasoning",
      topic: "Advanced Series",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "2n+1 pattern identified",
    },
    {
      id: "seed-d2b-13",
      date: DAY_TWO,
      session: "Elite Challenge",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Nearest-subject agreement",
    },
    {
      id: "seed-d2b-14",
      date: DAY_TWO,
      session: "Completion Set",
      subject: "Quantitative Aptitude",
      topic: "Squares & Cubes",
      attempted: 4,
      correct: 4,
      difficulty: "Easy",
      score: 5,
      notes: "Revision — perfect recall",
    },
    {
      id: "seed-d2b-15",
      date: DAY_TWO,
      session: "Completion Set",
      subject: "Quantitative Aptitude",
      topic: "Percentages",
      attempted: 4,
      correct: 4,
      difficulty: "Easy",
      score: 5,
      notes: "Revision — accurate mental calculation",
    },
    {
      id: "seed-d2b-16",
      date: DAY_TWO,
      session: "Completion Set",
      subject: "Reasoning",
      topic: "Mixed Series",
      attempted: 4,
      correct: 4,
      difficulty: "Easy",
      score: 5,
      notes: "No mistakes",
    },
    {
      id: "seed-d2b-17",
      date: DAY_TWO,
      session: "Completion Set",
      subject: "English",
      topic: "Sentence Correction",
      attempted: 3,
      correct: 3,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect accuracy",
    },

    // --- Day 3 · 34/40 across five sessions ---------------------------------
    {
      id: "seed-d3-1",
      date: DAY_THREE,
      session: "Session 1",
      subject: "Quantitative Aptitude",
      topic: "Ratio & Proportion",
      attempted: 6,
      correct: 5,
      difficulty: "Easy-Moderate",
      score: 4.5,
      notes: "One proportion mistake",
    },
    {
      id: "seed-d3-2",
      date: DAY_THREE,
      session: "Session 1",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect accuracy",
    },
    {
      id: "seed-d3-3",
      date: DAY_THREE,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Profit & Loss",
      attempted: 8,
      correct: 6,
      difficulty: "Moderate",
      score: 4,
      notes: "Loss and profit reading errors",
    },
    {
      id: "seed-d3-4",
      date: DAY_THREE,
      session: "Session 3",
      subject: "Quantitative Aptitude",
      topic: "Discount",
      attempted: 4,
      correct: 3,
      difficulty: "Moderate",
      score: 4,
      notes: "One discount percentage error",
    },
    {
      id: "seed-d3-5",
      date: DAY_THREE,
      session: "Session 3",
      subject: "Quantitative Aptitude",
      topic: "Mixed Percentages",
      attempted: 2,
      correct: 1,
      difficulty: "Moderate",
      score: 3.5,
      notes: "One mixed-percentage error",
    },
    {
      id: "seed-d3-6",
      date: DAY_THREE,
      session: "Session 3",
      subject: "Quantitative Aptitude",
      topic: "Ratio & Proportion",
      attempted: 1,
      correct: 1,
      difficulty: "Easy",
      score: 5,
      notes: "Revision — correct ratio combination",
    },
    {
      id: "seed-d3-7",
      date: DAY_THREE,
      session: "Session 3",
      subject: "Reasoning",
      topic: "Advanced Series",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Correct recursive pattern",
    },
    {
      id: "seed-d3-8",
      date: DAY_THREE,
      session: "Correction Drill",
      subject: "Quantitative Aptitude",
      topic: "Discount & Percentages Drill",
      attempted: 4,
      correct: 4,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect recovery after the Session 3 errors",
    },
    {
      id: "seed-d3-9",
      date: DAY_THREE,
      session: "Final Session",
      subject: "Quantitative Aptitude",
      topic: "Mixed Arithmetic",
      attempted: 6,
      correct: 6,
      difficulty: "Easy-Moderate",
      score: 5,
      notes: "Perfect final set",
    },
    {
      id: "seed-d3-10",
      date: DAY_THREE,
      session: "Final Session",
      subject: "Reasoning",
      topic: "Mixed Series",
      attempted: 4,
      correct: 4,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect final set",
    },
    {
      id: "seed-d3-11",
      date: DAY_THREE,
      session: "Final Session",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 2,
      correct: 1,
      difficulty: "Easy",
      score: 4,
      notes: "Collective noun error",
    },

    // --- Day 4 · 39/40 across four sessions --------------------------------
    {
      id: "seed-d4-1",
      date: DAY_FOUR,
      session: "Session 1",
      subject: "Quantitative Aptitude",
      topic: "Time & Work",
      attempted: 6,
      correct: 5,
      difficulty: "Easy-Moderate",
      score: 4.5,
      notes: "One combined-work mistake",
    },
    {
      id: "seed-d4-2",
      date: DAY_FOUR,
      session: "Session 1",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d4-3",
      date: DAY_FOUR,
      session: "Session 1",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 2,
      correct: 2,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d4-4",
      date: DAY_FOUR,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Time, Speed & Distance",
      attempted: 10,
      correct: 10,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d4-5",
      date: DAY_FOUR,
      session: "Session 3",
      subject: "Quantitative Aptitude",
      topic: "Simple Interest",
      attempted: 10,
      correct: 10,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d4-6",
      date: DAY_FOUR,
      session: "Final Session",
      subject: "Quantitative Aptitude",
      topic: "Mixed Arithmetic",
      attempted: 4,
      correct: 4,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect final set",
    },
    {
      id: "seed-d4-7",
      date: DAY_FOUR,
      session: "Final Session",
      subject: "Reasoning",
      topic: "Mixed Series",
      attempted: 3,
      correct: 3,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect final set",
    },
    {
      id: "seed-d4-8",
      date: DAY_FOUR,
      session: "Final Session",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 3,
      correct: 3,
      difficulty: "Easy",
      score: 5,
      notes: "Perfect final set",
    },

    // --- Day 5 · 44/46, every block at Moderate ---------------------------
    {
      id: "seed-d5-1",
      date: DAY_FIVE,
      session: "Learning + Practice",
      subject: "Quantitative Aptitude",
      topic: "Compound Interest",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Excellent CI understanding",
    },
    {
      id: "seed-d5-2",
      date: DAY_FIVE,
      session: "Learning + Practice",
      subject: "Quantitative Aptitude",
      topic: "Average",
      attempted: 10,
      correct: 9,
      difficulty: "Moderate",
      score: 4.5,
      notes: "One combined-average arithmetic slip",
    },
    {
      id: "seed-d5-3",
      date: DAY_FIVE,
      session: "Learning + Practice",
      subject: "Quantitative Aptitude",
      topic: "Successive Percentage",
      attempted: 7,
      correct: 7,
      difficulty: "Moderate",
      score: 5,
      notes: "Correct shortcut application",
    },
    {
      id: "seed-d5-4",
      date: DAY_FIVE,
      session: "Learning + Practice",
      subject: "Quantitative Aptitude",
      topic: "Partnership",
      attempted: 5,
      correct: 5,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect capital × time reasoning",
    },
    {
      id: "seed-d5-5",
      date: DAY_FIVE,
      session: "Learning + Practice",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 5,
      correct: 5,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect pattern recognition",
    },
    {
      id: "seed-d5-6",
      date: DAY_FIVE,
      session: "Final Mini-Test",
      subject: "Quantitative Aptitude",
      topic: "Mixed Arithmetic",
      attempted: 5,
      correct: 4,
      difficulty: "Moderate",
      score: 4.5,
      notes: "One successive-percentage direction error",
    },
    {
      id: "seed-d5-7",
      date: DAY_FIVE,
      session: "Final Mini-Test",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Correct",
    },
    {
      id: "seed-d5-8",
      date: DAY_FIVE,
      session: "Final Mini-Test",
      subject: "Quantitative Aptitude",
      topic: "Average",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Correct",
    },
    {
      id: "seed-d5-9",
      date: DAY_FIVE,
      session: "Final Mini-Test",
      subject: "Quantitative Aptitude",
      topic: "Partnership",
      attempted: 2,
      correct: 2,
      difficulty: "Moderate",
      score: 5,
      notes: "Correct",
    },

    // --- Day 6 · 40/40, the first questions above Moderate ------------------
    {
      id: "seed-d6-1",
      date: DAY_SIX,
      session: "Session 1",
      subject: "Quantitative Aptitude",
      topic: "Relative Speed & Boats",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d6-2",
      date: DAY_SIX,
      session: "Session 2",
      subject: "Quantitative Aptitude",
      topic: "Time, Speed & Distance",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d6-3",
      date: DAY_SIX,
      session: "Session 3",
      subject: "Quantitative Aptitude",
      topic: "Average & Compound Interest",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect; percentage traps correct",
    },
    {
      id: "seed-d6-4",
      date: DAY_SIX,
      session: "Final Session",
      subject: "Quantitative Aptitude",
      topic: "Mixed Arithmetic",
      attempted: 7,
      correct: 7,
      difficulty: "Moderate-Hard",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d6-5",
      date: DAY_SIX,
      session: "Final Session",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 2,
      correct: 2,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d6-6",
      date: DAY_SIX,
      session: "Final Session",
      subject: "Quantitative Aptitude",
      topic: "Partnership",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },

    // --- Day 7 · 37/40 over four rounds, the first Hard questions -----------
    {
      id: "seed-d7-1",
      date: DAY_SEVEN,
      session: "Round 1",
      subject: "Quantitative Aptitude",
      topic: "Mixed Quantitative",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect mixed-topic round",
    },
    {
      id: "seed-d7-2",
      date: DAY_SEVEN,
      session: "Round 2",
      subject: "Quantitative Aptitude",
      topic: "Advanced Mixed Quantitative",
      attempted: 7,
      correct: 7,
      difficulty: "Moderate-Hard",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d7-3",
      date: DAY_SEVEN,
      session: "Round 2",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 2,
      correct: 2,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d7-4",
      date: DAY_SEVEN,
      session: "Round 2",
      subject: "Quantitative Aptitude",
      topic: "Time & Work",
      attempted: 1,
      correct: 0,
      difficulty: "Moderate",
      score: 4,
      notes: "Answer-format trap — gave a percentage where a fraction was asked for",
    },
    {
      id: "seed-d7-5",
      date: DAY_SEVEN,
      session: "Round 3",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 10,
      correct: 8,
      difficulty: "Moderate",
      score: 4,
      notes: "Collective nouns and uncountable nouns need reinforcement",
    },
    {
      id: "seed-d7-6",
      date: DAY_SEVEN,
      session: "Round 4",
      subject: "Quantitative Aptitude",
      topic: "Mixed Advanced Quantitative",
      attempted: 8,
      correct: 8,
      difficulty: "Hard",
      score: 5,
      notes: "Perfect final round",
    },
    {
      id: "seed-d7-7",
      date: DAY_SEVEN,
      session: "Round 4",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 1,
      correct: 1,
      difficulty: "Hard",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d7-8",
      date: DAY_SEVEN,
      session: "Round 4",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 1,
      correct: 1,
      difficulty: "Hard",
      score: 5,
      notes: "Perfect",
    },

    // --- Day 8 · 39/40, the day the weak topics were finally revisited -----
    {
      id: "seed-d8-1",
      date: DAY_EIGHT,
      session: "Round 1",
      subject: "Quantitative Aptitude",
      topic: "Profit & Loss",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d8-2",
      date: DAY_EIGHT,
      session: "Round 2",
      subject: "Quantitative Aptitude",
      topic: "Time & Work",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d8-3",
      date: DAY_EIGHT,
      session: "Round 3",
      subject: "Quantitative Aptitude",
      topic: "Data Interpretation",
      attempted: 10,
      correct: 10,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
    {
      id: "seed-d8-4",
      date: DAY_EIGHT,
      session: "Round 4",
      subject: "English",
      topic: "Grammar Basics",
      attempted: 9,
      correct: 8,
      difficulty: "Moderate",
      score: 4,
      notes: "Uncountable noun error — “furniture is”",
    },
    {
      id: "seed-d8-5",
      date: DAY_EIGHT,
      session: "Round 4",
      subject: "Reasoning",
      topic: "Number Series",
      attempted: 1,
      correct: 1,
      difficulty: "Moderate",
      score: 5,
      notes: "Perfect",
    },
  ],
  topics: [
    {
      id: "seed-t1",
      subject: "Quantitative Aptitude",
      topic: "Percentages",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Excellent speed and accuracy across Day 2 and Day 3",
    },
    {
      id: "seed-t2",
      subject: "Quantitative Aptitude",
      topic: "Percentage Shortcuts",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Instant recall of 12.5%, 16⅔%, 33⅓%, 66⅔%",
    },
    // Day 1 listed one "Simplification & Approximation" topic; Day 2 practised
    // and scored the two halves separately, so they are two topics here.
    {
      id: "seed-t10",
      subject: "Quantitative Aptitude",
      topic: "Simplification",
      status: "Strong",
      targetAccuracy: 0.9,
      priority: "Medium",
      notes: "Day 2 completed with 100% accuracy",
    },
    {
      id: "seed-t11",
      subject: "Quantitative Aptitude",
      topic: "Approximation",
      status: "Strong",
      targetAccuracy: 0.9,
      priority: "Medium",
      notes: "Day 2 completed with 100% accuracy",
    },
    {
      id: "seed-t12",
      subject: "Quantitative Aptitude",
      topic: "Squares & Cubes",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "High",
      notes: "4/4 on Day 2; keep the tables to 30 sharp",
    },
    {
      id: "seed-t4",
      subject: "Reasoning",
      topic: "Number Series",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Perfect",
    },
    {
      id: "seed-t5",
      subject: "Reasoning",
      topic: "Coding-Decoding",
      status: "Strong",
      targetAccuracy: 0.9,
      priority: "Low",
      notes: "No mistakes in practice",
    },
    {
      id: "seed-t6",
      subject: "Reasoning",
      topic: "Odd One Out / Number Patterns",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Low",
      notes: "Improved pattern checking",
    },
    {
      id: "seed-t9",
      subject: "Quantitative Aptitude",
      topic: "Speed Percentage Drill",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "Timed mental-calculation drill",
    },
    // --- Topics first practised on Day 2 -----------------------------------
    {
      id: "seed-t13",
      subject: "Quantitative Aptitude",
      topic: "Squares Ending in 5",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "(n)(n+1)+25 trick",
    },
    {
      id: "seed-t14",
      subject: "Quantitative Aptitude",
      topic: "Fast Multiplication",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "Shortcut forms such as 999 × 9",
    },
    {
      id: "seed-t15",
      subject: "Quantitative Aptitude",
      topic: "Square Roots & Percentages",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "Fast root recognition",
    },
    {
      id: "seed-t16",
      subject: "Quantitative Aptitude",
      topic: "Difference of Squares",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "a²−b² identity",
    },
    {
      id: "seed-t17",
      subject: "Quantitative Aptitude",
      topic: "Mixed Quant",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Low",
      notes: "Mixed drill, not a syllabus topic",
    },
    {
      id: "seed-t18",
      subject: "Quantitative Aptitude",
      topic: "Speed Mock",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Low",
      notes: "Timed drill, not a syllabus topic",
    },
    {
      id: "seed-t19",
      subject: "Reasoning",
      topic: "Advanced Series",
      status: "Strong",
      targetAccuracy: 0.9,
      priority: "Low",
      notes: "Perfect recursive pattern recognition; Day 1 listed this as Complex Number Series",
    },
    {
      id: "seed-t20",
      subject: "Reasoning",
      topic: "Mixed Series",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Low",
      notes: "Mixed drill, not a syllabus topic",
    },
    {
      id: "seed-t21",
      subject: "English",
      topic: "Sentence Correction",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "3/3 on Day 2",
    },
    {
      id: "seed-t22",
      subject: "Quantitative Aptitude",
      topic: "Ratio & Proportion",
      status: "Strong",
      targetAccuracy: 0.9,
      priority: "Low",
      notes: "91.7% accuracy on Day 3",
    },
    {
      id: "seed-t8",
      subject: "English",
      topic: "Grammar Basics",
      status: "Developing",
      targetAccuracy: 0.88,
      priority: "High",
      notes: "Uncountable nouns remain the priority",
    },
    // --- Topics first practised or flagged on Day 3 -------------------------
    {
      id: "seed-t23",
      subject: "Quantitative Aptitude",
      topic: "Profit & Loss",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Day 8 perfect",
    },
    {
      id: "seed-t24",
      subject: "Quantitative Aptitude",
      topic: "Discount",
      status: "Developing",
      targetAccuracy: 0.85,
      priority: "High",
      notes: "One discount percentage error",
    },
    {
      id: "seed-t25",
      subject: "Quantitative Aptitude",
      topic: "Mixed Percentages",
      status: "Developing",
      targetAccuracy: 0.85,
      priority: "Medium",
      notes: "One mixed-percentage error",
    },
    {
      id: "seed-t26",
      subject: "Quantitative Aptitude",
      topic: "Discount & Percentages Drill",
      status: "Strong",
      targetAccuracy: 0.85,
      priority: "Low",
      notes: "Correction drill, not a syllabus topic",
    },
    {
      id: "seed-t27",
      subject: "Quantitative Aptitude",
      topic: "Mixed Arithmetic",
      status: "Strong",
      targetAccuracy: 0.9,
      priority: "Low",
      notes: "Perfect final sets on Day 3 and Day 4",
    },
    {
      id: "seed-t28",
      subject: "English",
      topic: "Collective Nouns",
      status: "Needs Work",
      targetAccuracy: 0.8,
      priority: "High",
      notes: "Committee has/have confusion",
    },
    // --- Topics first practised on Day 4 -------------------------------------
    {
      id: "seed-t29",
      subject: "Quantitative Aptitude",
      topic: "Time & Work",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Day 8 perfect",
    },
    {
      id: "seed-t30",
      subject: "Quantitative Aptitude",
      topic: "Time, Speed & Distance",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Excellent",
    },
    {
      id: "seed-t31",
      subject: "Quantitative Aptitude",
      topic: "Simple Interest",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Perfect Day 4",
    },
    // --- Topics first practised on Day 5 -------------------------------------
    {
      id: "seed-t32",
      subject: "Quantitative Aptitude",
      topic: "Compound Interest",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Excellent",
    },
    {
      id: "seed-t33",
      subject: "Quantitative Aptitude",
      topic: "Average",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Strong",
    },
    {
      id: "seed-t34",
      subject: "Quantitative Aptitude",
      topic: "Successive Percentage",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Day 7 traps handled correctly",
    },
    {
      id: "seed-t35",
      subject: "Quantitative Aptitude",
      topic: "Partnership",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Strong",
    },
    // --- Topics first practised on Day 6 -------------------------------------
    {
      id: "seed-t36",
      subject: "Quantitative Aptitude",
      topic: "Relative Speed & Boats",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Day 6 perfect — one block covering both relative speed and boats & streams",
    },
    {
      id: "seed-t37",
      subject: "Quantitative Aptitude",
      topic: "Average & Compound Interest",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Day 6 perfect — one block covering both, including the percentage traps",
    },
    // --- Topics first practised on Day 7 -------------------------------------
    {
      id: "seed-t38",
      subject: "Quantitative Aptitude",
      topic: "Mixed Quantitative",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Mixed-topic round, Day 7 perfect",
    },
    {
      id: "seed-t39",
      subject: "Quantitative Aptitude",
      topic: "Advanced Mixed Quantitative",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "Moderate-Hard round, Day 7 perfect",
    },
    {
      id: "seed-t40",
      subject: "Quantitative Aptitude",
      topic: "Mixed Advanced Quantitative",
      status: "Strong",
      targetAccuracy: 0.95,
      priority: "Low",
      notes: "The first Hard round, and perfect",
    },
    // --- Topics first practised on Day 8 -------------------------------------
    {
      id: "seed-t41",
      subject: "Quantitative Aptitude",
      topic: "Data Interpretation",
      status: "Strong",
      targetAccuracy: 0.98,
      priority: "Low",
      notes: "Day 8 perfect",
    },
  ],
  sessions: [
    {
      id: "seed-s1",
      date: DAY_ONE,
      sessionType: "Main + Afternoon",
      plannedFocus:
        "Percentages, Number Series, Coding-Decoding, English basics, speed drills",
      completed: true,
      keyStrength:
        "Percentages, mental calculation, basic pattern recognition",
      improvementArea:
        "Complex series and odd-one-out property checking",
      nextAction:
        "Day 1 completed; start Day 2 Simplification & Approximation",
    },
    {
      id: "seed-s2",
      date: DAY_TWO,
      sessionType: "Full Day",
      plannedFocus:
        "Session 1 + Session 2 + Elite Challenge + Completion Set — Simplification, Approximation, Squares, Cubes, Percentages, Reasoning, English",
      completed: true,
      keyStrength:
        "Simplification speed, percentage shortcuts, pattern recognition",
      improvementArea: "Maintain consistency under higher difficulty",
      nextAction: "Day 2 completed; start Day 3 Ratio & Proportion",
    },
    {
      id: "seed-s3",
      date: DAY_THREE,
      sessionType: "Full Day",
      plannedFocus:
        "Session 1 + Session 2 + Session 3 + Correction Drill + Final Session — Ratio, Proportion, Profit & Loss, Discount, Percentages, Reasoning, English",
      completed: true,
      keyStrength: "Reasoning, percentages, final arithmetic set",
      improvementArea:
        "Profit & Loss accuracy, discount, English collective nouns",
      nextAction: "Day 3 completed; start Day 4 Time & Work and SI/CI",
    },
    {
      id: "seed-s4",
      date: DAY_FOUR,
      sessionType: "Full Day",
      plannedFocus:
        "Session 1 + Session 2 + Session 3 + Final Session — Time & Work, Time-Speed-Distance, Simple Interest, Reasoning, English",
      completed: true,
      keyStrength: "TSD, SI, reasoning, English",
      improvementArea: "Combined-work interpretation",
      nextAction: "Day 4 completed; start Day 5",
    },
    {
      id: "seed-s5",
      date: DAY_FIVE,
      sessionType: "Learning + Practice",
      plannedFocus:
        "Learning + Practice + Final Mini-Test — Compound Interest, Average, Successive Percentage, Partnership, Number Series",
      completed: true,
      keyStrength: "Compound Interest, Partnership, Number Series",
      improvementArea:
        "Successive percentage direction/sign; combined-average arithmetic",
      nextAction: "Day 5 completed; Day 6 next",
    },
    {
      id: "seed-s6",
      date: DAY_SIX,
      sessionType: "Full Day",
      plannedFocus:
        "All sessions — Relative Speed, Boats & Streams, TSD, Average, CI, Partnership, Number Series",
      completed: true,
      keyStrength: "All listed topics",
      improvementArea: "No errors",
      nextAction: "Day 6 completed; Day 7 next",
    },
    {
      id: "seed-s7",
      date: DAY_SEVEN,
      sessionType: "Full Day",
      plannedFocus:
        "Round 1 + Round 2 + Round 3 + Round 4 — Mixed Quantitative, Reasoning, English",
      completed: true,
      keyStrength: "Quantitative strengths",
      improvementArea: "English grammar and answer-format precision",
      nextAction: "Day 7 completed; 7-day cycle complete",
    },
    {
      id: "seed-s8",
      date: DAY_EIGHT,
      sessionType: "Full Day",
      plannedFocus:
        "All rounds — Profit & Loss, Time & Work, Data Interpretation, English Grammar, Number Series",
      completed: true,
      keyStrength: "Profit & Loss, Time & Work, DI, Number Series",
      improvementArea: "English uncountable nouns",
      nextAction: "Day 8 completed; 39/40",
    },
  ],
};
